In [2]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC

In [4]:
from sklearn.datasets import load_breast_cancer

In [6]:
X,y = load_breast_cancer(return_X_y = True)
X,y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [9]:
from sklearn.model_selection import StratifiedKFold

In [7]:
model1 = SVC(probability = True)
model2 = SVC(C=10, probability = True)
model3 = SVC(kernel = 'poly', probability = True)

In [ ]:
#steps for max voting ensembling
# 1. modelswith parameters
# 2. cv accuracies of the model


In [29]:
split = StratifiedKFold()
accuracy = []


In [30]:
for train_index, test_index in split.split(X,y):
    model1.fit(X[train_index], y[train_index])
    model2.fit(X[train_index], y[train_index])
    model3.fit(X[train_index], y[train_index])
    
    
    all_preds = pd.DataFrame({'model1':model1.predict(X[test_index]),
                              'model2': model2.predict(X[test_index]), 
                              "model3":model3.predict(X[test_index])})

In [31]:
all_preds

model1  model2  model3
0         0       0       0
1         0       0       0
2         0       0       0
3         0       0       0
4         0       0       0
..      ...     ...     ...
108       0       0       0
109       0       0       0
110       0       0       0
111       0       0       0
112       1       1       1

[113 rows x 3 columns]

In [32]:
predict_final = all_preds.mode(axis=1)

In [33]:
np.sum(y[test_index] == predict_final.values.flatten())/len(test_index)

0.9380530973451328

In [34]:
predict_final.values

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
    

In [35]:

accuracy.append(np.sum(y[test_index] == predict_final.values.flatten())/len(test_index))

In [37]:
accuracy

[0.9380530973451328]

In [49]:
from sklearn.ensemble import RandomForestClassifier
import warnings 
warnings.filterwarnings('ignore')

In [57]:
for train_index, test_index in split.split(X,y):
    model1.fit(X[train_index], y[train_index])
    model2.fit(X[train_index], y[train_index])
    model3.fit(X[train_index], y[train_index])
    
    
    all_preds = pd.DataFrame({'model1':model1.predict_proba(X[test_index])[:,1],
                              'model2': model2.predict_proba(X[test_index])[:,1], 
                              "model3":model3.predict_proba(X[test_index])[:,1]})

    

In [60]:
predict_final = np.where(all_preds.mode(axis=1) > 0.6,1,0)
np.sum(y[test_index] == predict_final)/len(test_index)

0.0

In [51]:
accuracy =[]
accuracy.append(np.sum(y[test_index] == predict_final)/len(test_index))


In [52]:
accuracy

[0.0]

In [62]:
from sklearn.model_selection import cross_val_score

In [66]:
w1 = cross_val_score(SVC(probability = True),y)
w2 = cross_val_score(SVC(C=10, probability = True),X,y)
w3 = cross_val_score(SVC(kernel = 'poly', probability = True),X,y)

In [ ]:
for train_index, test_index in split.split(X,y):
    model1.fit(X[train_index], y[train_index])
    model2.fit(X[train_index], y[train_index])
    model3.fit(X[train_index], y[train_index])
    
    
    all_preds = pd.DataFrame({'W1':w1.predict(X[test_index]),
                              'W2':w2.predict(X[test_index]), 
                              "W3":w3.predict(X[test_index])})

    