In [1]:
import pandas as pd
import numpy as np

In [187]:
data = pd.read_csv('D:/rani/leukemia.csv',header = None)
data.head()

0     1     2     3     4     5     6     7     8     9     ...  7120  \
0  -342  -200    41   328  -224  -427  -656  -292   137  -144  ...  1023   
1   -87  -248   262   295  -226  -493   367  -452   194   162  ...   529   
2   -62   -23    -7   142  -233  -284  -167   -97   -12   -70  ...   383   
3    22  -153    17   276  -211  -250    55  -141     0   500  ...   399   
4    86   -36  -141   252  -201  -384  -420  -197   -60  -468  ...    91   

   7121  7122  7123  7124  7125  7126  7127  7128  7129  
0    67   214  -135  1074   475    48   168   -70   ALL  
1  -295   352   -67    67   263   -33   -33   -21   ALL  
2    46   104    15   245   164    84   100   -18   ALL  
3    16   558    24   893   297     6  1971   -42   ALL  
4   -84   615   -52  1235     9     7  1545   -81   ALL  

[5 rows x 7130 columns]

In [188]:
from sklearn.preprocessing import scale, LabelEncoder
x = scale(data.iloc[:,:-1])
X = pd.DataFrame(x)
X.head()

0         1         2         3         4         5         6     \
0 -2.343119 -0.417685  0.402727  1.247951  0.241532 -0.206876 -2.091222   
1  0.284197 -0.920478  2.216537  0.950933  0.225048 -0.649105  1.527248   
2  0.541777  1.436365  0.008777 -0.426151  0.167355  0.751286 -0.361572   
3  1.407245  0.074633  0.205752  0.779923  0.348676  0.979101  0.423668   
4  2.066650  1.300192 -1.090999  0.563909  0.431094  0.081243 -1.256462   

       7         8         9     ...      7119      7120      7121      7122  \
0 -1.021323  0.641052 -1.073110  ...  1.087451  1.168094  0.907318 -0.446436   
1 -2.634379  1.283042  0.282708  ... -0.987903 -0.459085 -3.263465 -0.079296   
2  0.944590 -1.037134 -0.745232  ... -0.495809 -0.939992  0.665367 -0.739084   
3  0.501000 -0.901978  1.780311  ...  2.542338 -0.887290  0.319722  0.468754   
4 -0.063570 -1.577757 -2.508682  ...  1.772104 -1.901807 -0.832428  0.620399   

       7123      7124      7125      7126      7127      7128  
0 -1.960424  0.654856  0.834169  0.862406 -0.428500 -0.987929  
1 -0.644876 -1.592384 -0.199669 -0.955286 -0.752918  0.239762  
2  0.941519 -1.195156 -0.682452  1.670269 -0.538254  0.314926  
3  1.115636  0.250933 -0.033865 -0.080101  2.481580 -0.286391  
4 -0.354682  1.014147 -1.438325 -0.057660  1.794007 -1.263533  

[5 rows x 7129 columns]

In [191]:
Y = data.iloc[:, -1]

In [192]:
label = LabelEncoder()
label.fit(Y)
y =label.transform(Y)

In [193]:
type(y)

numpy.ndarray

In [194]:
np.unique(y,return_counts= True)

(array([0, 1]), array([47, 25], dtype=int64))

In [198]:
from sklearn.model_selection import train_test_split
X_train, X_test ,Y_train, Y_test = train_test_split(X,y, test_size = 0.2, random_state =1)

In [199]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state = 42)
model.fit(X_train,Y_train)
Y_pred = model.predict(X_test)

In [200]:
from sklearn.metrics import accuracy_score, matthews_corrcoef, confusion_matrix, make_scorer
mcc = matthews_corrcoef(y_test, y_pred)
acc = accuracy_score(Y_test, Y_pred)

print("MCC: " , mcc)
print('Accurcy: ',acc)

MCC:  0.7844645405527361
Accurcy:  0.9333333333333333


### using  gini

In [202]:
from sklearn.model_selection import GridSearchCV
rfc = RandomForestClassifier(random_state = 42)

param_grid = {'n_estimators' : [50, 100, 200],
              'max_features' : [0.01, 0.1, 0.2, 0.5,'auto'],
              'max_depth': [None,10,20,50,100],
              'criterion': ['gini']}
grid = GridSearchCV(estimator = rfc,param_grid = param_grid, cv = 5, verbose = 1,n_jobs =-1 )
grid.fit(X,y)



Fitting 5 folds for each of 75 candidates, totalling 375 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   27.2s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  2.1min
[Parallel(n_jobs=-1)]: Done 375 out of 375 | elapsed:  4.1min finished


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['gini'],
                         'max_depth': [None, 10, 20, 50, 100],
                         'max_features': [0.01, 0.1, 0.2, 0.5, 'auto'],
                         'n_estimators': [50, 100, 200]},
             verbose=1)

In [2]:
clf = grid.best_estimator_
clf.fit(X_train,Y_train)
y_pred  = clf.predict(X_test)
matthews_corrcoef(Y_test, y_pred)

NameError: name 'grid' is not defined

In [3]:
print(grid.best_params_)

NameError: name 'grid' is not defined

In [206]:
feature_score = clf.feature_importances_


In [207]:
k =100
selected_features = feature_score.argsort()[-k:]
selected_features


array([ 237, 6687,  286, 2142, 3343,  952, 5713, 6429, 3592, 6547, 2837,
       5597, 6832, 6004, 3691, 2496, 6748, 5385, 4378, 2005,  980, 2323,
       5541, 5650,  360, 5656, 4106, 2241, 1259, 3182, 1077, 6805, 2019,
       3421, 3519, 1673, 4540,  378, 3257,  349,  757,   87, 4168, 3432,
       6538, 6701, 2120, 4498, 2591, 1828, 4195, 5334,  750, 2000, 1927,
       6572, 4779, 2401, 3347,  282, 1952, 6372, 1132, 1158, 2407,  873,
       1925, 1744, 5771, 2440, 5500, 5832, 6375, 7118, 1778, 2832, 1290,
       2140, 4365, 2641, 1143, 6280, 4327, 6040, 4228, 4893, 2110,  921,
       2127, 2353,  803, 1684, 4846,  759, 2287, 3251, 4376, 6854, 1881,
       1833], dtype=int64)

In [208]:
selected_features.shape

(100,)

In [209]:
X_new = X.iloc[:, selected_features]  ### gini
X_new.shape

(72, 100)

In [210]:
from sklearn.model_selection import train_test_split
x_train, x_test ,y_train, y_test = train_test_split(X_new,y, test_size = 0.2, random_state =1)

In [211]:
model = RandomForestClassifier(random_state= 42)
model.fit(x_train,y_train)
y_pred_gini = model.predict(x_test)
mcc = matthews_corrcoef(y_test, y_pred_gini)
acc = accuracy_score(y_test, y_pred_gini)
 
print('MCC :', mcc) 
print('Accuracy : ' , acc)

MCC : 1.0
Accuracy :  1.0


In [212]:
scorer = make_scorer(matthews_corrcoef)
mcc_cv = cross_val_score(rfc, X_new,y,cv=5,scoring = scorer)  ### gini  ### cross validation`
mcc_cv.mean()

0.9697056274847714

In [213]:
from sklearn.model_selection import StratifiedKFold
scorer = make_scorer(matthews_corrcoef)
kfold = StratifiedKFold(n_splits = 5)
mcc_cv = cross_val_score(rfc, X_new,y,cv=kfold,scoring = scorer)  ### gini  ##StratifiedKFold
mcc_cv.mean()

0.9697056274847714

### Using Entropy

In [214]:
from sklearn.model_selection import GridSearchCV
rfc = RandomForestClassifier(random_state = 42)

param_grid = {'n_estimators' : [50, 100, 200],
              'max_features' : [0.01, 0.1, 0.2, 0.5,'auto'],
              'max_depth': [None,10,20,50,100],
              'criterion': ['entropy']}
grid = GridSearchCV(estimator = rfc,param_grid = param_grid, cv = 5, verbose = 1,n_jobs =-1 )
grid.fit(X,y)

Fitting 5 folds for each of 75 candidates, totalling 375 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   32.4s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:  3.2min
[Parallel(n_jobs=-1)]: Done 375 out of 375 | elapsed:  6.3min finished


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'criterion': ['entropy'],
                         'max_depth': [None, 10, 20, 50, 100],
                         'max_features': [0.01, 0.1, 0.2, 0.5, 'auto'],
                         'n_estimators': [50, 100, 200]},
             verbose=1)

In [215]:
clf = grid.best_estimator_
clf.fit(X_train,Y_train)
y_pred  = clf.predict(X_test)
matthews_corrcoef(Y_test, y_pred)

1.0

In [216]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_depth': None, 'max_features': 0.01, 'n_estimators': 100}


In [217]:
feature_score = clf.feature_importances_

In [218]:
k =100
selected_features = feature_score.argsort()[-k:]
selected_features

array([2854, 2834, 6459, 5624, 5217, 3713, 4297, 3251, 1126, 1744, 4954,
       5128,  594, 1290, 3486, 1870,  531, 4188, 4323, 2829, 4152, 3065,
        274, 6675, 6462, 6583, 2347, 4972, 5535, 4327, 3388, 4460, 3846,
       1368, 5316, 2139, 3004, 2140, 4420,  258, 2267, 3432, 6998, 3680,
       1944, 5106, 1259, 5273, 4329, 6278, 2631, 6435, 4191, 6268, 6168,
       1724, 2083, 1901, 2738, 2744,  584, 3103, 1673,  697, 2110, 4679,
        342, 4779, 2641, 2407, 2994, 6711, 4372, 1881, 7118, 6040,  921,
        929, 3319, 2127, 3667, 1684, 3705, 6184, 3022, 4376, 2019, 3257,
       4106, 6280, 4365, 4228, 1778,  803, 1143, 2287, 6854, 2120,  759,
       1833], dtype=int64)

In [219]:
x_new = X.iloc[:, selected_features]  ### entropy
x_new.shape

(72, 100)

In [220]:
from sklearn.model_selection import train_test_split
x_trainE, x_testE ,y_trainE, y_testE = train_test_split(x_new,y, test_size = 0.2, random_state =1)

In [221]:
model = RandomForestClassifier(random_state= 42)
model.fit(x_trainE,y_trainE)
y_predE = model.predict(x_testE)
mcc = matthews_corrcoef(y_testE, y_predE)
 
print('MCC :', mcc) 
print('Accuracy : ' , acc)



MCC : 1.0
Accuracy :  1.0


In [222]:
from sklearn.model_selection import cross_val_score
scorer = make_scorer(matthews_corrcoef)
mcc_cv = cross_val_score(rfc, X,y,cv=5,scoring = scorer)  ### full data cross validation
mcc_cv.mean()

0.9697056274847714

In [223]:
scorer = make_scorer(matthews_corrcoef)
mcc_cv = cross_val_score(rfc, x_new,y,cv=5,scoring = scorer)  ### entropy ### crosss validation
mcc_cv.mean()

0.9697056274847714

In [224]:
from sklearn.model_selection import StratifiedKFold
scorer = make_scorer(matthews_corrcoef)
kfold = StratifiedKFold(n_splits = 5)
mcc_cv = cross_val_score(rfc, x_new,y,cv=kfold,scoring = scorer)  ### entropy
mcc_cv


array([1.        , 1.        , 0.84852814, 1.        , 1.        ])

In [225]:
mcc_cv.mean()

0.9697056274847714

In [226]:
#print(grid.cv_results_)
df = pd.DataFrame(grid.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.558996      0.010276         0.178527        0.009358   
1        0.932262      0.033332         0.199141        0.009018   
2        1.740894      0.062024         0.216354        0.006405   
3        1.306528      0.050134         0.166918        0.002318   
4        2.556215      0.088953         0.186333        0.004625   
..            ...           ...              ...             ...   
70       7.150480      0.324101         0.151508        0.003384   
71      13.553416      0.767302         0.161314        0.033150   
72       0.446716      0.009735         0.139700        0.002579   
73       0.744328      0.008548         0.152108        0.002759   
74       1.385172      0.048832         0.178327        0.004449   

   param_criterion param_max_depth param_max_features param_n_estimators  \
0          entropy            None               0.01                 50   
1          entropy            None               0.01                100   
2          entropy            None               0.01                200   
3          entropy            None                0.1                 50   
4          entropy            None                0.1                100   
..             ...             ...                ...                ...   
70         entropy             100                0.5                100   
71         entropy             100                0.5                200   
72         entropy             100               auto                 50   
73         entropy             100               auto                100   
74         entropy             100               auto                200   

                                               params  split0_test_score  \
0   {'criterion': 'entropy', 'max_depth': None, 'm...                1.0   
1   {'criterion': 'entropy', 'max_depth': None, 'm...                1.0   
2   {'criterion': 'entropy', 'max_depth': None, 'm...                1.0   
3   {'criterion': 'entropy', 'max_depth': None, 'm...                1.0   
4   {'criterion': 'entropy', 'max_depth': None, 'm...                1.0   
..                                                ...                ...   
70  {'criterion': 'entropy', 'max_depth': 100, 'ma...                1.0   
71  {'criterion': 'entropy', 'max_depth': 100, 'ma...                1.0   
72  {'criterion': 'entropy', 'max_depth': 100, 'ma...                1.0   
73  {'criterion': 'entropy', 'max_depth': 100, 'ma...                1.0   
74  {'criterion': 'entropy', 'max_depth': 100, 'ma...                1.0   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.933333           0.928571           1.000000   
1            1.000000           0.928571           1.000000   
2            0.933333           0.928571           1.000000   
3            0.933333           0.857143           0.928571   
4            0.933333           0.928571           1.000000   
..                ...                ...                ...   
70           0.933333           0.857143           0.928571   
71           0.933333           0.928571           0.928571   
72           1.000000           0.928571           1.000000   
73           1.000000           0.928571           1.000000   
74           1.000000           0.928571           1.000000   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            1.000000         0.972381        0.033860               11  
1            1.000000         0.985714        0.028571                1  
2            1.000000         0.972381        0.033860               11  
3            1.000000         0.943810        0.053231               46  
4            1.000000         0.972381        0.033860               11  
..                ...              ...             ...              ...  
70           0.928571         0.929524        0.045216               61  
71          